// Bundle shared algorithms into a self-contained worklet factory. This avoids
// maintaining a second implementation or calling Metro require on a worker.
const fs = require('node:fs');
const path = require('node:path');
const esbuild = require('esbuild');
const babel = require('@babel/core');
function build() {
  const result = esbuild.buildSync({
    entryPoints: [path.resolve(__dirname, '../src/performance/computeOperations.js')],
    bundle: true, platform: 'browser', format: 'iife', globalName: 'BiuCompute',
    target: 'es2020', write: false, legalComments: 'inline',
  });
  // Worklets evaluates source in a separate Hermes runtime. Its eval compiler
  // does not preserve per-iteration let bindings: esbuild's export getters would
  // all read the last export (e.g. Buffer becomes kMaxLength). Lower scope BEFORE
  // Worklets serializes the factory, including esbuild's generated helpers.
  const bundled = babel.transformSync(result.outputFiles[0].text, {
    configFile: false, babelrc: false,
    plugins: [require.resolve('@babel/plugin-transform-block-scoping')],
  }).code;
  const output = "// Generated by scripts/build-compute.cjs; do not edit.\nmodule.exports = function createCompute() {\n'worklet';\n"
    // fflate has optional browser fast paths. Use its bundled UTF-8 fallback;
    // native JS constructors cannot be captured as Worklet class factories.
    + 'const WorkerGlobalScope = undefined, TextDecoder = undefined, TextEncoder = undefined;\n'
    + bundled + '\nreturn BiuCompute.compute;\n};\n';
  const file = path.resolve(__dirname, '../src/performance/compute.generated.js');
  if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== output) {
    const temporary = file + '.' + process.pid + '.tmp';
    fs.writeFileSync(temporary, output); fs.renameSync(temporary, file);
  }
  return file;
}
module.exports = build;
if (require.main === module) build();
